// Generated by scripts/generate-host-display.mjs — do not edit.
export const HOST_PAGE_COUNT = 6 as const;
export const CORE_KNOB_COUNT = 8 as const;
export const EXPANDED_CORE_KNOB_COUNT = 10 as const;
export const PAIR_AR_KNOB_COUNT = 4 as const;
export const TOTAL_KNOB_COUNT = EXPANDED_CORE_KNOB_COUNT + PAIR_AR_KNOB_COUNT;
export const HOST_PAGE_NAMES = ["Audio","Random S&H","Reverb","Filter","Drive","Delay"] as const;
export const HOST_PAGE_KNOB_LABELS: readonly (readonly string[])[] = [["VCO1","VCO2","VCO3","Cross-coupler","Phase mod 1","Phase mod 2","Phase mod 3","Crispy"],["Step chance","Deja vu 1","Bag size 1","Slew 1","Deja vu 2","Bag size 2","Slew 2","Spread","Bias","Crispy"],["Wet/dry","Room size","Decay","Pre-delay","Damping","Stereo width","Diffusion","Mod depth","Hold","Crispy"],["Comb offset","Peak freq","Peak gain","Peak Q","Comb delay","Comb feedback","Comb LP","Comb/Peak","Scoop","Crispy"],["Drive","Shape","SRR 1","SRR 2","XOR","Bit depth","Fuzz","Blend","Phase","Crispy"],["Delay time","Send","Feedback","Stereo width","Detune","Mod depth","Wet mix","Color","Halo","Crispy"]];
export const PAIR_AR_KNOB_LABELS = ["Attack 1+2","Release 1+2","Attack 2+3","Release 2+3"] as const;
export const GLOBAL_STRIP_LABELS = ["Rand All","Rand Mods","Rand Resample","Rand waveforms"] as const;
export const SCOPE_SIZE = 96 as const;
export const MOD_LED_FULL_BRIGHTNESS_CV = 0.55 as const;
export const WEB_MOD_BAY_SPEC = [{"modIndex":0,"kind":"scope"},{"modIndex":4,"kind":"scope"},{"modIndex":5,"kind":"led"},{"modIndex":6,"kind":"led"}] as const;
export const WEB_SCOPE_MOD_INDICES = [0,4,5,6] as const;
export const DESKTOP_MOD_RACK_INDICES = [0,1,4,5,6] as const;
export const VST_MOD_RACK_INDICES = [4,5,6] as const;
export const VCV_MOD_RACK_INDICES = [4,5,6] as const;

export type ModBaySpec = { modIndex: number; kind: "scope" | "led" };

export function modLedDisplayBrightness(cv01: number, active: boolean): number {
  if (!active) {
    return 0;
  }
  const clamped = Math.min(Math.max(cv01, 0), 1);
  if (clamped >= MOD_LED_FULL_BRIGHTNESS_CV) {
    return 1;
  }
  const normalized = clamped / MOD_LED_FULL_BRIGHTNESS_CV;
  return normalized * normalized;
}

export function coreKnobCountForPage(hostPage: number): number {
  return hostPage === 0 ? CORE_KNOB_COUNT : EXPANDED_CORE_KNOB_COUNT;
}

export function coreKnobLabel(hostPage: number, row: number): string {
  return HOST_PAGE_KNOB_LABELS[hostPage]?.[row] ?? "";
}

export function pairArKnobLabel(index: number): string {
  return PAIR_AR_KNOB_LABELS[index] ?? "";
}
